// Project Euler Problem 2

// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


// Pseudocode
// Using the first two integers of the Fibonacci sequence, build the sequence as an array
// Stop adding to the array once the final element is greater than 4,000,000
// Using an accumulator, check each Fibonacci number and add all the evens together


